### ISSUE TITLE
Properly initialize servo values

### ISSUE THREAD

**Issue by notzane** [MaretEngineering/MROV#31]
The servos all start at 0 but they should start at the "center" value for the camera and open for the claw (make these constants because we will have to change them when we get the mechanical specs from @ddworken or @vishnuramasawmy) 

Also, create variables (probably arrays) for the range of values that the servos operate on and replace those in the code.

**Comment by notzane** [comment]
@Eclip5e5 did you do this?

**Comment by Eclip5e5** [comment]
I did for pan and tilt, but not for the new claw because I don't know the range.
