### ISSUE TITLE
Change if(debug) statements to #ifdef

### ISSUE THREAD

**Issue by Eclip5e5** [MaretEngineering/MROV#6]
Make the code _slightly_ more efficient and stream lined

**Comment by notzane** [comment]
[Here's](https://cs50.harvard.edu/resources/cppreference.com/preprocessor/preprocessor_if.html) how to use ifdef statements

**Comment by notzane** [comment]
Also, if anyone is wondering why its more efficient, it's because when you use preprocessor statements (like ifdef), and it evaluates to false, it doesn't compile that portion of the code, which saves space and processing time on the Arduino later on.
